# Generated by Django 3.2 on 2023-07-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
