# Generated by Django 3.2 on 2023-07-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0005_permision'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='conse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='finish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='progres',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Conse',
        ),
    ]
