# Generated by Django 3.2 on 2023-07-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0006_auto_20230726_1211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movil',
        ),
    ]
