# Generated by Django 3.2 on 2023-07-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0007_delete_movil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='active',
        ),
        migrations.RemoveField(
            model_name='document',
            name='conse',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created',
        ),
        migrations.RemoveField(
            model_name='document',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='document',
            name='progres',
        ),
    ]
