# Generated by Django 3.2 on 2023-09-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0008_auto_20230726_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='wsp',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
