# Generated by Django 3.2 on 2024-07-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0010_auto_20240316_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='amarilla',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='infobel',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
