# Generated by Django 5.1 on 2025-04-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0012_userpangea'),
    ]

    operations = [
        migrations.AddField(
            model_name='permision',
            name='peoplecall',
            field=models.BooleanField(default=False),
        ),
    ]
