# Generated by Django 5.1 on 2025-06-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0013_permision_peoplecall'),
    ]

    operations = [
        migrations.AddField(
            model_name='permision',
            name='movil_individual',
            field=models.BooleanField(default=False),
        ),
    ]
