# Generated by Django 5.1 on 2025-11-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movil', '0014_permision_movil_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='permision',
            name='wsp',
            field=models.BooleanField(default=False),
        ),
    ]
