# Generated by Django 4.2.20 on 2025-04-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peoplecall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='document',
        ),
        migrations.AddField(
            model_name='consecutive',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movil.document'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='consecutive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='peoplecall.consecutive'),
        ),
    ]
