# Generated by Django 4.2.20 on 2025-04-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplecall', '0002_remove_phonenumber_document_consecutive_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='fromRaw_p',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='from_p',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='toRaw_p',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='to_p',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='when_p',
            field=models.CharField(default='', max_length=100),
        ),
    ]
